sudo: required

services:
  - docker

before_install:
- docker build -t dyngb-trusty -f ./travis_custom/Dockerfile .
- docker run dyngb-trusty:latest sudo git clone https://github.com/stack-of-tasks/dynamic_graph_bridge.git /repo

script:
- docker run dyngb-trusty:latest sudo mkdir /build
- docker run dyngb-trusty:latest sudo -c "cd /build;cmake ../repo"
- docker run dyngb-trusty:latest sudo -c "cd /build;make"
